name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  VERSION: 3.16.1
  RELEASE: 3.16
  ACTIONS_RUNNER_DEBUG: true

permissions:
  contents: write
  packages: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Disabled s360x as was failing checksumming
        arch: ["aarch64", "armhf", "armv7", "ppc64le", "x86", "x86_64"]
    steps:
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: archive  # Remember to give an ID if you need the output
        name: Download the file
        with:
          url: "https://dl-cdn.alpinelinux.org/alpine/v${{ env.RELEASE }}/releases/${{ matrix.arch }}/alpine-netboot-${{ env.VERSION }}-${{ matrix.arch }}.tar.gz"
          target: ./
          auto-match: false
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: asc  # Remember to give an ID if you need the output
        name: Download the file
        with:
          url: "https://dl-cdn.alpinelinux.org/alpine/v${{ env.RELEASE }}/releases/${{ matrix.arch }}/alpine-netboot-${{ env.VERSION }}-${{ matrix.arch }}.tar.gz.asc"
          target: ./
          auto-match: false
      - name: Import Alpine Linux GPG key
        run: |
          curl https://alpinelinux.org/keys/ncopa.asc | gpg --import
      - name: Verify downloaded artifact
        run: |
          gpg --verify alpine-netboot-${{ env.VERSION }}-${{ matrix.arch }}.tar.gz.asc alpine-netboot-${{ env.VERSION }}-${{ matrix.arch }}.tar.gz
  manifest:
    needs: fetch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Buildah action
        uses: actions/checkout@v3
        with:
          repository: 'redhat-actions/buildah-build'
          path: "buildah-build"

      - name: Install latest buildah
        run: |
          bash buildah-build/.github/install_latest_buildah.sh
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Create manifest
        run: |
          ARCHITECTURES="aarch64 armhf armv7 ppc64le s360x x86 x86_64"
          VERSION=$(cat version.txt | cut -d 'v' -f 2)
          RELEASE=$(echo "$VERSION" | cut -d '.' -f 1-2)
          MANIFEST=ghcr.io/oci-base/alpine

          buildah manifest create "$MANIFEST:v$VERSION"
          for arch in $(echo $ARCHITECTURES); do
            ctr=$(buildah from --arch "$arch" scratch)
            buildah add "$ctr" https://dl-cdn.alpinelinux.org/alpine/"$RELEASE/releases/$arch/alpine-netboot-$VERSION-$arch".tar.gz
            buildah commit --manifest "$MANIFEST:v$VERSION" "$ctr" "$MANIFEST:$VERSION-$arch"
          done
          echo "$GITHUB_TOKEN" | buildah login -u "$GITHUB_ACTOR" --password-stdin ghcr.io
          buildah manifest push --all "$MANIFEST:v$VERSION" docker://"$MANIFEST:v$VERSION"
